name: Test composite action
on:
  pull_request:
    paths:
      - 'action.yml'
  workflow_dispatch:    

jobs:
  test-composite-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: master
          repository: falcosecurity/libs
          path: libs
    
      - name: Test action
        uses: ./
        with:
          repo-root: libs

      - name: Show diff
        working-directory: libs
        run: git diff
